server:
  port: 8090

spring:
  application:
    name: common
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 6000ms

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  #开启驼峰映射，详情在XML文件中
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'

# redis缓存
cache-expire:
  captcha: 100
  account: 3600
  order: 36000

# 机器位置: 机房ID,机柜ID
counter:
  data-center-id: 0
  worker-id: 0
