spring:
  profiles:
    active: common
  application:
    name: ${sequence.name}

server:
  servlet:
    context-path: ${sequence.context-path}
  port: ${sequence.port}

sequence:
  data-paths: D:/server1/,D:/server2/,D:/server3/
  serve-urls: 127.0.0.1:8891,127.0.0.1:8892,127.0.0.1:8893


